# Site/SEO settings
email: 
permalink: /:year/:month/:day/:title/
google_analytics: 

title: Trophy
description: 
url: ""
baseurl: ""
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: "/blog/page-:num"
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  categories: 
      layouts: 
        - 'category_index.html'
      # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
      title: ':cat'
      # Optional, the permalink for the  pagination page (:cat is replaced), 
      # the pagination permalink path is then appended to this permalink structure
      permalink: '/category/:cat'
      slugify:
        mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
        case: false       # Whether to replace all uppercase letters with their lowercase counterparts

# Sass
sass:
  style: compressed
